# Uncomment this line to define a global platform for your project
# platform :ios, '13.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

source 'https://github.com/appodeal/CocoaPods.git'
source 'https://cdn.cocoapods.org/'

# platform :ios, '12.0'

# def appodeal
#   pod 'APDAdColonyAdapter', '3.0.2.1'
#   pod 'BidMachineAdColonyAdapter', '~> 2.0.0.0'
#   pod 'APDAdjustAdapter', '3.0.2.1'
#   pod 'APDAppLovinAdapter', '3.0.2.1'
#   pod 'APDAppsFlyerAdapter', '3.0.2.1'
#   pod 'APDBidMachineAdapter', '3.0.2.1' # Required
#   pod 'BidMachineAmazonAdapter', '~> 2.0.0.0'
#   pod 'BidMachineCriteoAdapter', '~> 2.0.0.0'
#   pod 'BidMachineSmaatoAdapter', '~> 2.0.0.0'
#   pod 'BidMachineTapjoyAdapter', '~> 2.0.0.0'
#   pod 'BidMachinePangleAdapter', '~> 2.0.0.0'
#   pod 'BidMachineNotsyAdapter', '~> 2.0.0.4'
#   pod 'APDFirebaseAdapter', '3.0.2.1'
#   pod 'APDGoogleAdMobAdapter', '3.0.2.1'
#   pod 'APDIABAdapter', '3.0.2.1' # Required
#   pod 'APDIronSourceAdapter', '3.0.2.1'
#   pod 'APDFacebookAdapter', '3.0.2.1'
#   pod 'APDMetaAudienceNetworkAdapter', '3.0.2.1'
#   pod 'BidMachineMetaAudienceAdapter', '~> 2.0.0.0'
#   pod 'APDMyTargetAdapter', '3.0.2.1'
#   pod 'BidMachineMyTargetAdapter', '~> 2.0.0.2'
#   pod 'APDStackAnalyticsAdapter', '3.0.2.1' # Required
#   pod 'APDUnityAdapter', '3.0.2.1'
#   pod 'APDVungleAdapter', '3.0.2.1'
#   pod 'BidMachineVungleAdapter', '~> 2.0.0.1'
#   pod 'APDYandexAdapter', '3.0.2.1'
# end

target 'Runner' do
  use_frameworks!
  use_modular_headers!
  # appodeal

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
  target 'RunnerTests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)

    target.build_configurations.each do |config|
      # You can remove unused permissions here
      # for more information: https://github.com/BaseflowIT/flutter-permission-handler/blob/master/permission_handler/ios/Classes/PermissionHandlerEnums.h
      # e.g. when you don't need camera permission, just add 'PERMISSION_CAMERA=0'
      config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= [
        '$(inherited)',

        ## dart: PermissionGroup.calendar
        #'PERMISSION_EVENTS=1',
        
        ## dart: PermissionGroup.calendarFullAccess
        #'PERMISSION_EVENTS_FULL_ACCESS=1',

        ## dart: PermissionGroup.reminders
        #'PERMISSION_REMINDERS=1',

        ## dart: PermissionGroup.contacts
        #'PERMISSION_CONTACTS=1',

        ## dart: PermissionGroup.camera
        #'PERMISSION_CAMERA=0',

        ## dart: PermissionGroup.microphone
        'PERMISSION_MICROPHONE=1',

        ## dart: PermissionGroup.speech
        'PERMISSION_SPEECH_RECOGNIZER=1',

        ## dart: PermissionGroup.photos
        #'PERMISSION_PHOTOS=1',

        ## The 'PERMISSION_LOCATION' macro enables the `locationWhenInUse` and `locationAlways` permission. If
        ## the application only requires `locationWhenInUse`, only specify the `PERMISSION_LOCATION_WHENINUSE`
        ## macro.
        ##
        ## dart: [PermissionGroup.location, PermissionGroup.locationAlways, PermissionGroup.locationWhenInUse]
        #'PERMISSION_LOCATION=1',
        #'PERMISSION_LOCATION_WHENINUSE=0',

        ## dart: PermissionGroup.notification
        #'PERMISSION_NOTIFICATIONS=1',

        ## dart: PermissionGroup.mediaLibrary
        #'PERMISSION_MEDIA_LIBRARY=1',

        ## dart: PermissionGroup.sensors
        #'PERMISSION_SENSORS=1',

        ## dart: PermissionGroup.bluetooth
        #'PERMISSION_BLUETOOTH=1',

        ## dart: PermissionGroup.appTrackingTransparency
        # 'PERMISSION_APP_TRACKING_TRANSPARENCY=1',

        ## dart: PermissionGroup.criticalAlerts
        #'PERMISSION_CRITICAL_ALERTS=1',

        ## dart: PermissionGroup.criticalAlerts
        #'PERMISSION_ASSISTANT=1',
      ]

    end
  end
end
